const RECORDS_PER_FETCH = 5;

export const data = [
  {
    "_id": 72,
    "title": "Edit Distance",
    "difficulty": "Hard",
    "topic": "String, Dynamic Programming,",
    "company": "Microsoft",
    "typeOfInterview": "Online Test",
    "college": "IIIT, Hyderabad",
    "natureOfJob": "Full Time",
    "score": 95.633,
    "description": "Implement a trie with insert, search, and startsWith methods."
  },
  {
    "_id": 1143,
    "title": "Longest Common Subsequence",
    "difficulty": "Medium",
    "topic": "Dynamic Programming,",
    "company": "PayPal",
    "typeOfInterview": "Personal Interview",
    "college": "IIT, Delhi",
    "natureOfJob": "Full Time",
    "score": 91.045,
    "description": "Invert a binary tree."
  },
  {
    "_id": 42,
    "title": "Trapping Rain Water",
    "difficulty": "Hard",
    "topic": "Array, Two Pointers, Stack,",
    "company": "Jio",
    "typeOfInterview": "Online Test",
    "college": "IIT, BHU",
    "natureOfJob": "Internship",
    "score": 85.653,
    "description": "Given two strings word1 and word2, return the minimum number of operations required to convert word1 to word2.\n\nYou have the following three operations permitted on a word:\n\nInsert a character\nDelete a character\nReplace a character"
  },
  {
    "_id": 1151,
    "title": "Minimum Swaps to Group All 1's Together",
    "difficulty": "Medium",
    "topic": "Array, Sliding Window,",
    "company": "DeMux",
    "typeOfInterview": "Personal Interview",
    "college": "IIIT, Una",
    "natureOfJob": "Internship",
    "score": 78.868,
    "description": "Invert a binary tree."
  },
  {
    "_id": 208,
    "title": "Implement Trie (Prefix Tree)",
    "difficulty": "Medium",
    "topic": "Design, Trie,",
    "company": "Microsoft",
    "typeOfInterview": "Personal Interview",
    "college": "IIIT, Una",
    "natureOfJob": "Trainee",
    "score": 90.878,
    "description": "Given two strings word1 and word2, return the minimum number of operations required to convert word1 to word2.\n\nYou have the following three operations permitted on a word:\n\nInsert a character\nDelete a character\nReplace a character"
  },
  {
    "_id": 226,
    "title": "Invert Binary Tree",
    "difficulty": "Easy",
    "topic": "Tree,",
    "company": "LinkedIn",
    "typeOfInterview": "Personal Interview",
    "college": "IIIT, Una",
    "natureOfJob": "Full Time",
    "score": 85.775,
    "description": "Given two strings text1 and text2, return the length of their longest common subsequence.\n\nA subsequence of a string is a new string generated from the original string with some characters(can be none) deleted without changing the relative order of the remaining characters. (eg, \"ace\" is a subsequence of \"abcde\" while \"aec\" is not). A common subsequence of two strings is a subsequence that is common to both strings"
  },
  {
    "_id": 253,
    "title": "Meeting Rooms II",
    "difficulty": "Medium",
    "topic": "Heap, Greedy, Sort,",
    "company": "Adobe",
    "typeOfInterview": "Online Test",
    "college": "IIIT, Guwahati",
    "natureOfJob": "Part Time",
    "score": 95.694,
    "description": "Given two strings word1 and word2, return the minimum number of operations required to convert word1 to word2.\n\nYou have the following three operations permitted on a word:\n\nInsert a character\nDelete a character\nReplace a character"
  },
  {
    "_id": 206,
    "title": "Reverse Linked List",
    "difficulty": "Easy",
    "topic": "Linked List,",
    "company": "Xebia",
    "typeOfInterview": "Online Test",
    "college": "IIT, BHU",
    "natureOfJob": "Trainee",
    "score": 93.01,
    "description": "Invert a binary tree."
  },
  {
    "_id": 286,
    "title": "Walls and Gates",
    "difficulty": "Medium",
    "topic": "Breadth-first Search,",
    "company": "Morgan Stanley",
    "typeOfInterview": "Online Test",
    "college": "IIIT, Una",
    "natureOfJob": "Internship",
    "score": 90.904,
    "description": "Given two strings text1 and text2, return the length of their longest common subsequence.\n\nA subsequence of a string is a new string generated from the original string with some characters(can be none) deleted without changing the relative order of the remaining characters. (eg, \"ace\" is a subsequence of \"abcde\" while \"aec\" is not). A common subsequence of two strings is a subsequence that is common to both strings"
  },
  {
    "_id": 295,
    "title": "Find Median from Data Stream",
    "difficulty": "Hard",
    "topic": "Heap, Design,",
    "company": "Facebook",
    "typeOfInterview": "Personal Interview",
    "college": "NIT, Hamirpur",
    "natureOfJob": "Internship",
    "score": 80.601,
    "description": "Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining."
  },
  {
    "_id": 990,
    "title": "Satisfiability of Equality Equations",
    "difficulty": "Medium",
    "topic": "Union Find, Graph,",
    "company": "Xebia",
    "typeOfInterview": "Personal Interview",
    "college": "IIIT, Guwahati",
    "natureOfJob": "Part Time",
    "score": 78.764,
    "description": "Given two strings text1 and text2, return the length of their longest common subsequence.\n\nA subsequence of a string is a new string generated from the original string with some characters(can be none) deleted without changing the relative order of the remaining characters. (eg, \"ace\" is a subsequence of \"abcde\" while \"aec\" is not). A common subsequence of two strings is a subsequence that is common to both strings"
  },
  {
    "_id": 1439,
    "title": "Find the Kth Smallest Sum of a Matrix With Sorted Rows",
    "difficulty": "Hard",
    "topic": "Heap,",
    "company": "Morgan Stanley",
    "typeOfInterview": "Personal Interview",
    "college": "IIIT, Guwahati",
    "natureOfJob": "Full Time",
    "score": 78.945,
    "description": "Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining."
  },
  {
    "_id": 366,
    "title": "Find Leaves of Binary Tree",
    "difficulty": "Medium",
    "topic": "Tree, Depth-first Search,",
    "company": "Adobe",
    "typeOfInterview": "Online Test",
    "college": "SRMS",
    "natureOfJob": "Part Time",
    "score": 97.987,
    "description": "Given two strings word1 and word2, return the minimum number of operations required to convert word1 to word2.\n\nYou have the following three operations permitted on a word:\n\nInsert a character\nDelete a character\nReplace a character"
  },
  {
    "_id": 337,
    "title": "House Robber III",
    "difficulty": "Medium",
    "topic": "Tree, Depth-first Search,",
    "company": "LinkedIn",
    "typeOfInterview": "Online Test",
    "college": "IIT, Roorkee",
    "natureOfJob": "Full Time",
    "score": 93.029,
    "description": "Given two strings word1 and word2, return the minimum number of operations required to convert word1 to word2.\n\nYou have the following three operations permitted on a word:\n\nInsert a character\nDelete a character\nReplace a character"
  },
  {
    "_id": 329,
    "title": "Longest Increasing Path in a Matrix",
    "difficulty": "Hard",
    "topic": "Depth-first Search, Topological Sort, Memoization,",
    "company": "LinkedIn",
    "typeOfInterview": "Online Test",
    "college": "IIT, Delhi",
    "natureOfJob": "Internship",
    "score": 92.949,
    "description": "Given two strings text1 and text2, return the length of their longest common subsequence.\n\nA subsequence of a string is a new string generated from the original string with some characters(can be none) deleted without changing the relative order of the remaining characters. (eg, \"ace\" is a subsequence of \"abcde\" while \"aec\" is not). A common subsequence of two strings is a subsequence that is common to both strings"
  },
  {
    "_id": 64,
    "title": "Minimum Path Sum",
    "difficulty": "Medium",
    "topic": "Hash Table, Stack,",
    "company": "Adobe",
    "typeOfInterview": "Online Test",
    "college": "SRMS",
    "natureOfJob": "Full Time",
    "score": 97.964,
    "description": "Invert a binary tree."
  },
  {
    "_id": 895,
    "title": "Maximum Frequency Stack",
    "difficulty": "Hard",
    "topic": "Array, Dynamic Programming,",
    "company": "Google",
    "typeOfInterview": "Online Test",
    "college": "IIIT, Hyderabad",
    "natureOfJob": "Internship",
    "score": 90.054,
    "description": "Given two strings word1 and word2, return the minimum number of operations required to convert word1 to word2.\n\nYou have the following three operations permitted on a word:\n\nInsert a character\nDelete a character\nReplace a character"
  },
  {
    "_id": 78,
    "title": "Subsets",
    "difficulty": "Medium",
    "topic": "Array, Backtracking, Bit Manipulation,",
    "company": "Morgan Stanley",
    "typeOfInterview": "Personal Interview",
    "college": "NIT, Hamirpur",
    "natureOfJob": "Internship",
    "score": 92.935,
    "description": "Given two strings word1 and word2, return the minimum number of operations required to convert word1 to word2.\n\nYou have the following three operations permitted on a word:\n\nInsert a character\nDelete a character\nReplace a character"
  },
  {
    "_id": 84,
    "title": "Largest Rectangle in Histogram",
    "difficulty": "Hard",
    "topic": "Array, Stack,",
    "company": "Jio",
    "typeOfInterview": "Online Test",
    "college": "IIT, BHU",
    "natureOfJob": "Trainee",
    "score": 92.981,
    "description": "Given two strings word1 and word2, return the minimum number of operations required to convert word1 to word2.\n\nYou have the following three operations permitted on a word:\n\nInsert a character\nDelete a character\nReplace a character"
  },
  {
    "_id": 300,
    "title": "Longest Increasing Subsequence",
    "difficulty": "Medium",
    "topic": "Binary Search, Dynamic Programming,",
    "company": "Facebook",
    "typeOfInterview": "Personal Interview",
    "college": "IIIT, Una",
    "natureOfJob": "Internship",
    "score": 80.298,
    "description": "Given an array equations of strings that represent relationships between variables, each string equations[i] has length 4 and takes one of two different forms: \"a==b\" or \"a!=b\".  Here, a and b are lowercase letters (not necessarily different) that represent one-letter variable names.\n\nReturn true if and only if it is possible to assign integers to variable names so as to satisfy all the given equations."
  },
  {
    "_id": 863,
    "title": "All Nodes Distance K in Binary Tree",
    "difficulty": "Medium",
    "topic": "Tree, Depth-first Search, Breadth-first Search,",
    "company": "Morgan Stanley",
    "typeOfInterview": "Online Test",
    "college": "SRMS",
    "natureOfJob": "Trainee",
    "score": 79.954,
    "description": "Given two strings text1 and text2, return the length of their longest common subsequence.\n\nA subsequence of a string is a new string generated from the original string with some characters(can be none) deleted without changing the relative order of the remaining characters. (eg, \"ace\" is a subsequence of \"abcde\" while \"aec\" is not). A common subsequence of two strings is a subsequence that is common to both strings"
  },
  {
    "_id": 958,
    "title": "Check Completeness of a Binary Tree",
    "difficulty": "Medium",
    "topic": "Tree,",
    "company": "LinkedIn",
    "typeOfInterview": "Online Test",
    "college": "IIIT, Una",
    "natureOfJob": "Internship",
    "score": 91.085,
    "description": "Invert a binary tree."
  },
  {
    "_id": 106,
    "title": "Construct Binary Tree from Inorder and Postorder Traversal",
    "difficulty": "Medium",
    "topic": "Array, Tree, Depth-first Search,",
    "company": "Xebia",
    "typeOfInterview": "Personal Interview",
    "college": "IIIT, Una",
    "natureOfJob": "Internship",
    "score": 90.885,
    "description": "Implement a trie with insert, search, and startsWith methods."
  },
  {
    "_id": 101,
    "title": "Symmetric Tree",
    "difficulty": "Easy",
    "topic": "Tree, Depth-first Search, Breadth-first Search,",
    "company": "LinkedIn",
    "typeOfInterview": "Online Test",
    "college": "NIT, Hamirpur",
    "natureOfJob": "Internship",
    "score": 93.122,
    "description": "Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining."
  },
  {
    "_id": 159,
    "title": "Longest Substring with At Most Two Distinct Characters",
    "difficulty": "Medium",
    "topic": "Hash Table, Two Pointers, String, Sliding Window,",
    "company": "Jio",
    "typeOfInterview": "Online Test",
    "college": "SRMS",
    "natureOfJob": "Part Time",
    "score": 79.015,
    "description": "Given two strings text1 and text2, return the length of their longest common subsequence.\n\nA subsequence of a string is a new string generated from the original string with some characters(can be none) deleted without changing the relative order of the remaining characters. (eg, \"ace\" is a subsequence of \"abcde\" while \"aec\" is not). A common subsequence of two strings is a subsequence that is common to both strings"
  },
  {
    "_id": 1277,
    "title": "Count Square Submatrices with All Ones",
    "difficulty": "Medium",
    "topic": "Array, Dynamic Programming,",
    "company": "Microsoft",
    "typeOfInterview": "Online Test",
    "college": "IIT, Delhi",
    "natureOfJob": "Internship",
    "score": 95.772,
    "description": "Given an array equations of strings that represent relationships between variables, each string equations[i] has length 4 and takes one of two different forms: \"a==b\" or \"a!=b\".  Here, a and b are lowercase letters (not necessarily different) that represent one-letter variable names.\n\nReturn true if and only if it is possible to assign integers to variable names so as to satisfy all the given equations."
  },
  {
    "_id": 1434,
    "title": "Number of Ways to Wear Different Hats to Each Other",
    "difficulty": "Hard",
    "topic": "Dynamic Programming, Bit Manipulation,",
    "company": "Facebook",
    "typeOfInterview": "Online Test",
    "college": "IIIT, Una",
    "natureOfJob": "Full Time",
    "score": 85.925,
    "description": "Given two strings text1 and text2, return the length of their longest common subsequence.\n\nA subsequence of a string is a new string generated from the original string with some characters(can be none) deleted without changing the relative order of the remaining characters. (eg, \"ace\" is a subsequence of \"abcde\" while \"aec\" is not). A common subsequence of two strings is a subsequence that is common to both strings"
  },
  {
    "_id": 487,
    "title": "Max Consecutive Ones II",
    "difficulty": "Medium",
    "topic": "Two Pointers,",
    "company": "Morgan Stanley",
    "typeOfInterview": "Online Test",
    "college": "IIIT, Hyderabad",
    "natureOfJob": "Internship",
    "score": 78.718,
    "description": "Given two strings word1 and word2, return the minimum number of operations required to convert word1 to word2.\n\nYou have the following three operations permitted on a word:\n\nInsert a character\nDelete a character\nReplace a character"
  },
  {
    "_id": 240,
    "title": "Search a 2D Matrix II",
    "difficulty": "Medium",
    "topic": "Binary Search, Divide and Conquer,",
    "company": "Facebook",
    "typeOfInterview": "Online Test",
    "college": "IIIT, Hyderabad",
    "natureOfJob": "Internship",
    "score": 95.597,
    "description": "Given an array equations of strings that represent relationships between variables, each string equations[i] has length 4 and takes one of two different forms: \"a==b\" or \"a!=b\".  Here, a and b are lowercase letters (not necessarily different) that represent one-letter variable names.\n\nReturn true if and only if it is possible to assign integers to variable names so as to satisfy all the given equations."
  },
  {
    "_id": 992,
    "title": "Subarrays with K Different Integers",
    "difficulty": "Hard",
    "topic": "Hash Table, Two Pointers, Sliding Window,",
    "company": "Facebook",
    "typeOfInterview": "Personal Interview",
    "college": "IIIT, Una",
    "natureOfJob": "Part Time",
    "score": 95.611,
    "description": "Given two strings text1 and text2, return the length of their longest common subsequence.\n\nA subsequence of a string is a new string generated from the original string with some characters(can be none) deleted without changing the relative order of the remaining characters. (eg, \"ace\" is a subsequence of \"abcde\" while \"aec\" is not). A common subsequence of two strings is a subsequence that is common to both strings"
  },
  {
    "_id": 983,
    "title": "Minimum Cost For Tickets",
    "difficulty": "Medium",
    "topic": "Dynamic Programming,",
    "company": "Facebook",
    "typeOfInterview": "Online Test",
    "college": "IIIT, Una",
    "natureOfJob": "Trainee",
    "score": 95.574,
    "description": "Implement a trie with insert, search, and startsWith methods."
  },
  {
    "_id": 102,
    "title": "Binary Tree Level Order Traversal",
    "difficulty": "Medium",
    "topic": "Tree, Breadth-first Search,",
    "company": "PayPal",
    "typeOfInterview": "Personal Interview",
    "college": "IIIT, Hyderabad",
    "natureOfJob": "Part Time",
    "score": 86.063,
    "description": "Implement a trie with insert, search, and startsWith methods."
  },
  {
    "_id": 1004,
    "title": "Max Consecutive Ones III",
    "difficulty": "Medium",
    "topic": "Two Pointers, Sliding Window,",
    "company": "Xebia",
    "typeOfInterview": "Online Test",
    "college": "IIIT, Una",
    "natureOfJob": "Trainee",
    "score": 90.846,
    "description": "Implement a trie with insert, search, and startsWith methods."
  },
  {
    "_id": 221,
    "title": "Maximal Square",
    "difficulty": "Medium",
    "topic": "Dynamic Programming,",
    "company": "Xebia",
    "typeOfInterview": "Personal Interview",
    "college": "IIT, Roorkee",
    "natureOfJob": "Part Time",
    "score": 91.025,
    "description": "Given two strings word1 and word2, return the minimum number of operations required to convert word1 to word2.\n\nYou have the following three operations permitted on a word:\n\nInsert a character\nDelete a character\nReplace a character"
  },
  {
    "_id": 85,
    "title": "Maximal Rectangle",
    "difficulty": "Hard",
    "topic": "Array, Hash Table, Dynamic Programming, Stack,",
    "company": "PayPal",
    "typeOfInterview": "Personal Interview",
    "college": "NIT, Hamirpur",
    "natureOfJob": "Trainee",
    "score": 95.558,
    "description": "Invert a binary tree."
  },
  {
    "_id": 230,
    "title": "Kth Smallest Element in a BST",
    "difficulty": "Medium",
    "topic": "Binary Search, Tree,",
    "company": "LinkedIn",
    "typeOfInterview": "Personal Interview",
    "college": "IIT, BHU",
    "natureOfJob": "Part Time",
    "score": 93.44,
    "description": "Given two strings text1 and text2, return the length of their longest common subsequence.\n\nA subsequence of a string is a new string generated from the original string with some characters(can be none) deleted without changing the relative order of the remaining characters. (eg, \"ace\" is a subsequence of \"abcde\" while \"aec\" is not). A common subsequence of two strings is a subsequence that is common to both strings"
  },
  {
    "_id": 1235,
    "title": "Maximum Profit in Job Scheduling",
    "difficulty": "Hard",
    "topic": "Binary Search, Dynamic Programming, Sort,",
    "company": "DeMux",
    "typeOfInterview": "Personal Interview",
    "college": "IIIT, Una",
    "natureOfJob": "Part Time",
    "score": 98.182,
    "description": "Implement a trie with insert, search, and startsWith methods."
  },
  {
    "_id": 1406,
    "title": "Stone Game III",
    "difficulty": "Hard",
    "topic": "Dynamic Programming,",
    "company": "Adobe",
    "typeOfInterview": "Personal Interview",
    "college": "IIIT, Hyderabad",
    "natureOfJob": "Full Time",
    "score": 92.987,
    "description": "Given two strings word1 and word2, return the minimum number of operations required to convert word1 to word2.\n\nYou have the following three operations permitted on a word:\n\nInsert a character\nDelete a character\nReplace a character"
  },
  {
    "_id": 174,
    "title": "Dungeon Game",
    "difficulty": "Hard",
    "topic": "Binary Search, Dynamic Programming,",
    "company": "PayPal",
    "typeOfInterview": "Online Test",
    "college": "IIIT, Una",
    "natureOfJob": "Trainee",
    "score": 79.841,
    "description": "Implement a trie with insert, search, and startsWith methods."
  },
  {
    "_id": 1293,
    "title": "Shortest Path in a Grid with Obstacles Elimination",
    "difficulty": "Hard",
    "topic": "Breadth-first Search,",
    "company": "DeMux",
    "typeOfInterview": "Online Test",
    "college": "NIT, Hamirpur",
    "natureOfJob": "Internship",
    "score": 79.886,
    "description": "Given an array equations of strings that represent relationships between variables, each string equations[i] has length 4 and takes one of two different forms: \"a==b\" or \"a!=b\".  Here, a and b are lowercase letters (not necessarily different) that represent one-letter variable names.\n\nReturn true if and only if it is possible to assign integers to variable names so as to satisfy all the given equations."
  },
  {
    "_id": 871,
    "title": "Minimum Number of Refueling Stops",
    "difficulty": "Hard",
    "topic": "Dynamic Programming, Heap,",
    "company": "Microsoft",
    "typeOfInterview": "Personal Interview",
    "college": "IIT, BHU",
    "natureOfJob": "Internship",
    "score": 86.002,
    "description": "Invert a binary tree."
  },
  {
    "_id": 46,
    "title": "Permutations",
    "difficulty": "Medium",
    "topic": "Backtracking,",
    "company": "Facebook",
    "typeOfInterview": "Personal Interview",
    "college": "IIIT, Una",
    "natureOfJob": "Internship",
    "score": 90.858,
    "description": "Given an array equations of strings that represent relationships between variables, each string equations[i] has length 4 and takes one of two different forms: \"a==b\" or \"a!=b\".  Here, a and b are lowercase letters (not necessarily different) that represent one-letter variable names.\n\nReturn true if and only if it is possible to assign integers to variable names so as to satisfy all the given equations."
  },
  {
    "_id": 1319,
    "title": "Number of Operations to Make Network Connected",
    "difficulty": "Medium",
    "topic": "Depth-first Search, Breadth-first Search, Union Find,",
    "company": "DeMux",
    "typeOfInterview": "Personal Interview",
    "college": "IIIT, Una",
    "natureOfJob": "Internship",
    "score": 80.321,
    "description": "Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining."
  },
  {
    "_id": 407,
    "title": "Trapping Rain Water II",
    "difficulty": "Hard",
    "topic": "Heap, Breadth-first Search,",
    "company": "Xebia",
    "typeOfInterview": "Online Test",
    "college": "IIIT, Guwahati",
    "natureOfJob": "Full Time",
    "score": 78.753,
    "description": "Given two strings text1 and text2, return the length of their longest common subsequence.\n\nA subsequence of a string is a new string generated from the original string with some characters(can be none) deleted without changing the relative order of the remaining characters. (eg, \"ace\" is a subsequence of \"abcde\" while \"aec\" is not). A common subsequence of two strings is a subsequence that is common to both strings"
  },
  {
    "_id": 632,
    "title": "Smallest Range Covering Elements from K Lists",
    "difficulty": "Hard",
    "topic": "Hash Table, Two Pointers, String,",
    "company": "Morgan Stanley",
    "typeOfInterview": "Personal Interview",
    "college": "NIT, Hamirpur",
    "natureOfJob": "Trainee",
    "score": 80.131,
    "description": "Given two strings word1 and word2, return the minimum number of operations required to convert word1 to word2.\n\nYou have the following three operations permitted on a word:\n\nInsert a character\nDelete a character\nReplace a character"
  },
  {
    "_id": 105,
    "title": "Construct Binary Tree from Preorder and Inorder Traversal",
    "difficulty": "Medium",
    "topic": "Array, Tree, Depth-first Search,",
    "company": "Adobe",
    "typeOfInterview": "Online Test",
    "college": "IIT, BHU",
    "natureOfJob": "Full Time",
    "score": 97.598,
    "description": "Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining."
  },
  {
    "_id": 416,
    "title": "Partition Equal Subset Sum",
    "difficulty": "Medium",
    "topic": "Dynamic Programming,",
    "company": "DeMux",
    "typeOfInterview": "Online Test",
    "college": "IIT, Delhi",
    "natureOfJob": "Internship",
    "score": 97.602,
    "description": "Given an array equations of strings that represent relationships between variables, each string equations[i] has length 4 and takes one of two different forms: \"a==b\" or \"a!=b\".  Here, a and b are lowercase letters (not necessarily different) that represent one-letter variable names.\n\nReturn true if and only if it is possible to assign integers to variable names so as to satisfy all the given equations."
  },
  {
    "_id": 312,
    "title": "Burst Balloons",
    "difficulty": "Hard",
    "topic": "Divide and Conquer, Dynamic Programming,",
    "company": "DeMux",
    "typeOfInterview": "Online Test",
    "college": "IIIT, Una",
    "natureOfJob": "Full Time",
    "score": 78.972,
    "description": "Invert a binary tree."
  },
  {
    "_id": 583,
    "title": "Delete Operation for Two Strings",
    "difficulty": "Medium",
    "topic": "String,",
    "company": "PayPal",
    "typeOfInterview": "Personal Interview",
    "college": "IIT, Delhi",
    "natureOfJob": "Full Time",
    "score": 78.883,
    "description": "Implement a trie with insert, search, and startsWith methods."
  },
  {
    "_id": 198,
    "title": "House Robber",
    "difficulty": "Easy",
    "topic": "Dynamic Programming,",
    "company": "Facebook",
    "typeOfInterview": "Online Test",
    "college": "IIIT, Una",
    "natureOfJob": "Internship",
    "score": 86.077,
    "description": "Given two strings word1 and word2, return the minimum number of operations required to convert word1 to word2.\n\nYou have the following three operations permitted on a word:\n\nInsert a character\nDelete a character\nReplace a character"
  },
  {
    "_id": 39,
    "title": "Combination Sum",
    "difficulty": "Medium",
    "topic": "Array, Backtracking,",
    "company": "Adobe",
    "typeOfInterview": "Online Test",
    "college": "IIIT, Una",
    "natureOfJob": "Full Time",
    "score": 78.894,
    "description": "Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining."
  },
  {
    "_id": 100,
    "title": "Same Tree",
    "difficulty": "Easy",
    "topic": "Tree, Depth-first Search,",
    "company": "LinkedIn",
    "typeOfInterview": "Personal Interview",
    "college": "IIT, BHU",
    "natureOfJob": "Trainee",
    "score": 78.953,
    "description": "description"
  },
  {
    "_id": 104,
    "title": "Maximum Depth of Binary Tree",
    "difficulty": "Easy",
    "topic": "Tree, Depth-first Search,",
    "company": "DeMux",
    "typeOfInterview": "Personal Interview",
    "college": "NIT, Hamirpur",
    "natureOfJob": "Trainee",
    "score": 80.235,
    "description": "Given two strings text1 and text2, return the length of their longest common subsequence.\n\nA subsequence of a string is a new string generated from the original string with some characters(can be none) deleted without changing the relative order of the remaining characters. (eg, \"ace\" is a subsequence of \"abcde\" while \"aec\" is not). A common subsequence of two strings is a subsequence that is common to both strings"
  },
  {
    "_id": 968,
    "title": "Binary Tree Cameras",
    "difficulty": "Hard",
    "topic": "Dynamic Programming, Tree, Depth-first Search,",
    "company": "DeMux",
    "typeOfInterview": "Personal Interview",
    "college": "IIIT, Guwahati",
    "natureOfJob": "Full Time",
    "score": 80.456,
    "description": "Invert a binary tree."
  },
  {
    "_id": 678,
    "title": "Valid Parenthesis String",
    "difficulty": "Medium",
    "topic": "String,",
    "company": "Google",
    "typeOfInterview": "Personal Interview",
    "college": "IIIT, Una",
    "natureOfJob": "Full Time",
    "score": 79.009,
    "description": "Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining."
  },
  {
    "_id": 739,
    "title": "Daily Temperatures",
    "difficulty": "Medium",
    "topic": "Hash Table, Stack,",
    "company": "DeMux",
    "typeOfInterview": "Personal Interview",
    "college": "IIT, Roorkee",
    "natureOfJob": "Full Time",
    "score": 95.744,
    "description": "Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining."
  },
  {
    "_id": 213,
    "title": "House Robber II",
    "difficulty": "Medium",
    "topic": "Dynamic Programming,",
    "company": "Adobe",
    "typeOfInterview": "Personal Interview",
    "college": "IIT, BHU",
    "natureOfJob": "Trainee",
    "score": 90.785,
    "description": "Given an array equations of strings that represent relationships between variables, each string equations[i] has length 4 and takes one of two different forms: \"a==b\" or \"a!=b\".  Here, a and b are lowercase letters (not necessarily different) that represent one-letter variable names.\n\nReturn true if and only if it is possible to assign integers to variable names so as to satisfy all the given equations."
  },
  {
    "_id": 1035,
    "title": "Uncrossed Lines",
    "difficulty": "Medium",
    "topic": "Array,",
    "company": "DeMux",
    "typeOfInterview": "Online Test",
    "college": "IIT, BHU",
    "natureOfJob": "Part Time",
    "score": 89.964,
    "description": "Implement a trie with insert, search, and startsWith methods."
  },
  {
    "_id": 1358,
    "title": "Number of Substrings Containing All Three Characters",
    "difficulty": "Medium",
    "topic": "String,",
    "company": "Microsoft",
    "typeOfInterview": "Personal Interview",
    "college": "SRMS",
    "natureOfJob": "Internship",
    "score": 89.77,
    "description": "Invert a binary tree."
  },
  {
    "_id": 129,
    "title": "Sum Root to Leaf Numbers",
    "difficulty": "Medium",
    "topic": "Tree, Depth-first Search,",
    "company": "PayPal",
    "typeOfInterview": "Personal Interview",
    "college": "IIIT, Una",
    "natureOfJob": "Part Time",
    "score": 95.574,
    "description": "Given an array equations of strings that represent relationships between variables, each string equations[i] has length 4 and takes one of two different forms: \"a==b\" or \"a!=b\".  Here, a and b are lowercase letters (not necessarily different) that represent one-letter variable names.\n\nReturn true if and only if it is possible to assign integers to variable names so as to satisfy all the given equations."
  },
  {
    "_id": 1482,
    "title": "Minimum Number of Days to Make m Bouquets",
    "difficulty": "Medium",
    "topic": "Array, Binary Search,",
    "company": "Morgan Stanley",
    "typeOfInterview": "Online Test",
    "college": "IIT, Delhi",
    "natureOfJob": "Internship",
    "score": 90.894,
    "description": "Given an array equations of strings that represent relationships between variables, each string equations[i] has length 4 and takes one of two different forms: \"a==b\" or \"a!=b\".  Here, a and b are lowercase letters (not necessarily different) that represent one-letter variable names.\n\nReturn true if and only if it is possible to assign integers to variable names so as to satisfy all the given equations."
  },
  {
    "_id": 322,
    "title": "Coin Change",
    "difficulty": "Medium",
    "topic": "Dynamic Programming,",
    "company": "Morgan Stanley",
    "typeOfInterview": "Online Test",
    "college": "IIIT, Guwahati",
    "natureOfJob": "Trainee",
    "score": 95.651,
    "description": "Given an array equations of strings that represent relationships between variables, each string equations[i] has length 4 and takes one of two different forms: \"a==b\" or \"a!=b\".  Here, a and b are lowercase letters (not necessarily different) that represent one-letter variable names.\n\nReturn true if and only if it is possible to assign integers to variable names so as to satisfy all the given equations."
  },
  {
    "_id": 560,
    "title": "Subarray Sum Equals K",
    "difficulty": "Medium",
    "topic": "Array, Hash Table,",
    "company": "Facebook",
    "typeOfInterview": "Personal Interview",
    "college": "IIIT, Guwahati",
    "natureOfJob": "Full Time",
    "score": 97.988,
    "description": "Given two strings text1 and text2, return the length of their longest common subsequence.\n\nA subsequence of a string is a new string generated from the original string with some characters(can be none) deleted without changing the relative order of the remaining characters. (eg, \"ace\" is a subsequence of \"abcde\" while \"aec\" is not). A common subsequence of two strings is a subsequence that is common to both strings"
  },
  {
    "_id": 70,
    "title": "Climbing Stairs",
    "difficulty": "Easy",
    "topic": "Dynamic Programming,",
    "company": "Google",
    "typeOfInterview": "Personal Interview",
    "college": "IIIT, Hyderabad",
    "natureOfJob": "Full Time",
    "score": 95.754,
    "description": "Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining."
  },
  {
    "_id": 323,
    "title": "Number of Connected Components in an Undirected Graph",
    "difficulty": "Medium",
    "topic": "Depth-first Search, Breadth-first Search, Union Find, Graph,",
    "company": "Adobe",
    "typeOfInterview": "Online Test",
    "college": "IIIT, Una",
    "natureOfJob": "Full Time",
    "score": 85.956,
    "description": "Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining."
  },
  {
    "_id": 283,
    "title": "Move Zeroes",
    "difficulty": "Easy",
    "topic": "Array, Two Pointers,",
    "company": "Adobe",
    "typeOfInterview": "Online Test",
    "college": "SRMS",
    "natureOfJob": "Full Time",
    "score": 89.997,
    "description": "Given two strings text1 and text2, return the length of their longest common subsequence.\n\nA subsequence of a string is a new string generated from the original string with some characters(can be none) deleted without changing the relative order of the remaining characters. (eg, \"ace\" is a subsequence of \"abcde\" while \"aec\" is not). A common subsequence of two strings is a subsequence that is common to both strings"
  },
  {
    "_id": 1,
    "title": "Two Sum",
    "difficulty": "Easy",
    "topic": "Array, Hash Table,",
    "company": "Jio",
    "typeOfInterview": "Personal Interview",
    "college": "IIIT, Guwahati",
    "natureOfJob": "Full Time",
    "score": 89.826,
    "description": "Given two strings text1 and text2, return the length of their longest common subsequence.\n\nA subsequence of a string is a new string generated from the original string with some characters(can be none) deleted without changing the relative order of the remaining characters. (eg, \"ace\" is a subsequence of \"abcde\" while \"aec\" is not). A common subsequence of two strings is a subsequence that is common to both strings"
  },
  {
    "_id": 200,
    "title": "Number of Islands",
    "difficulty": "Medium",
    "topic": "Depth-first Search, Breadth-first Search, Union Find,",
    "company": "Microsoft",
    "typeOfInterview": "Online Test",
    "college": "IIIT, Una",
    "natureOfJob": "Full Time",
    "score": 97.911,
    "description": "Given two strings text1 and text2, return the length of their longest common subsequence.\n\nA subsequence of a string is a new string generated from the original string with some characters(can be none) deleted without changing the relative order of the remaining characters. (eg, \"ace\" is a subsequence of \"abcde\" while \"aec\" is not). A common subsequence of two strings is a subsequence that is common to both strings"
  },
  {
    "_id": 518,
    "title": "Coin Change 2",
    "difficulty": "Medium",
    "topic": "",
    "company": "LinkedIn",
    "typeOfInterview": "Online Test",
    "college": "SRMS",
    "natureOfJob": "Full Time",
    "score": 89.995,
    "description": "Invert a binary tree."
  },
  {
    "_id": 862,
    "title": "Shortest Subarray with Sum at Least K",
    "difficulty": "Hard",
    "topic": "Binary Search, Queue,",
    "company": "Xebia",
    "typeOfInterview": "Online Test",
    "college": "NIT, Hamirpur",
    "natureOfJob": "Trainee",
    "score": 80.608,
    "description": "Invert a binary tree."
  },
  {
    "_id": 305,
    "title": "Number of Islands II",
    "difficulty": "Hard",
    "topic": "Union Find,",
    "company": "LinkedIn",
    "typeOfInterview": "Online Test",
    "college": "SRMS",
    "natureOfJob": "Full Time",
    "score": 90.024,
    "description": "Given two strings text1 and text2, return the length of their longest common subsequence.\n\nA subsequence of a string is a new string generated from the original string with some characters(can be none) deleted without changing the relative order of the remaining characters. (eg, \"ace\" is a subsequence of \"abcde\" while \"aec\" is not). A common subsequence of two strings is a subsequence that is common to both strings"
  },
  {
    "_id": 714,
    "title": "Best Time to Buy and Sell Stock with Transaction Fee",
    "difficulty": "Medium",
    "topic": "Array, Dynamic Programming, Greedy,",
    "company": "Adobe",
    "typeOfInterview": "Personal Interview",
    "college": "IIIT, Una",
    "natureOfJob": "Full Time",
    "score": 85.824,
    "description": "Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining."
  },
  {
    "_id": 47,
    "title": "Permutations II",
    "difficulty": "Medium",
    "topic": "Backtracking,",
    "company": "Adobe",
    "typeOfInterview": "Personal Interview",
    "college": "IIT, Roorkee",
    "natureOfJob": "Full Time",
    "score": 90.79,
    "description": "Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining."
  },
  {
    "_id": 986,
    "title": "Interval List Intersections",
    "difficulty": "Medium",
    "topic": "Two Pointers,",
    "company": "Morgan Stanley",
    "typeOfInterview": "Online Test",
    "college": "IIIT, Guwahati",
    "natureOfJob": "Trainee",
    "score": 90.782,
    "description": "Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining."
  },
  {
    "_id": 1008,
    "title": "Construct Binary Search Tree from Preorder Traversal",
    "difficulty": "Medium",
    "topic": "Tree,",
    "company": "DeMux",
    "typeOfInterview": "Online Test",
    "college": "IIIT, Hyderabad",
    "natureOfJob": "Internship",
    "score": 98.102,
    "description": "Given two strings word1 and word2, return the minimum number of operations required to convert word1 to word2.\n\nYou have the following three operations permitted on a word:\n\nInsert a character\nDelete a character\nReplace a character"
  },
  {
    "_id": 136,
    "title": "Single Number",
    "difficulty": "Easy",
    "topic": "Hash Table, Bit Manipulation,",
    "company": "Xebia",
    "typeOfInterview": "Personal Interview",
    "college": "IIIT, Una",
    "natureOfJob": "Full Time",
    "score": 93.021,
    "description": "Given two strings text1 and text2, return the length of their longest common subsequence.\n\nA subsequence of a string is a new string generated from the original string with some characters(can be none) deleted without changing the relative order of the remaining characters. (eg, \"ace\" is a subsequence of \"abcde\" while \"aec\" is not). A common subsequence of two strings is a subsequence that is common to both strings"
  },
  {
    "_id": 582,
    "title": "Kill Process",
    "difficulty": "Medium",
    "topic": "Tree, Queue,",
    "company": "Facebook",
    "typeOfInterview": "Personal Interview",
    "college": "IIIT, Guwahati",
    "natureOfJob": "Internship",
    "score": 89.737,
    "description": "Given an array equations of strings that represent relationships between variables, each string equations[i] has length 4 and takes one of two different forms: \"a==b\" or \"a!=b\".  Here, a and b are lowercase letters (not necessarily different) that represent one-letter variable names.\n\nReturn true if and only if it is possible to assign integers to variable names so as to satisfy all the given equations."
  },
  {
    "_id": 886,
    "title": "Possible Bipartition",
    "difficulty": "Medium",
    "topic": "Depth-first Search,",
    "company": "Google",
    "typeOfInterview": "Online Test",
    "college": "IIIT, Una",
    "natureOfJob": "Full Time",
    "score": 79.908,
    "description": "Given two strings text1 and text2, return the length of their longest common subsequence.\n\nA subsequence of a string is a new string generated from the original string with some characters(can be none) deleted without changing the relative order of the remaining characters. (eg, \"ace\" is a subsequence of \"abcde\" while \"aec\" is not). A common subsequence of two strings is a subsequence that is common to both strings"
  },
  {
    "_id": 787,
    "title": "Cheapest Flights Within K Stops",
    "difficulty": "Medium",
    "topic": "Dynamic Programming, Heap, Breadth-first Search,",
    "company": "Google",
    "typeOfInterview": "Personal Interview",
    "college": "SRMS",
    "natureOfJob": "Internship",
    "score": 92.941,
    "description": "Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining."
  },
  {
    "_id": 1011,
    "title": "Capacity To Ship Packages Within D Days",
    "difficulty": "Medium",
    "topic": "Array, Binary Search,",
    "company": "Xebia",
    "typeOfInterview": "Online Test",
    "college": "IIT, BHU",
    "natureOfJob": "Internship",
    "score": 79.781,
    "description": "Implement a trie with insert, search, and startsWith methods."
  },
  {
    "_id": 1325,
    "title": "Delete Leaves With a Given Value",
    "difficulty": "Medium",
    "topic": "Tree,",
    "company": "Facebook",
    "typeOfInterview": "Online Test",
    "college": "IIT, Delhi",
    "natureOfJob": "Internship",
    "score": 93.045,
    "description": "Given two strings text1 and text2, return the length of their longest common subsequence.\n\nA subsequence of a string is a new string generated from the original string with some characters(can be none) deleted without changing the relative order of the remaining characters. (eg, \"ace\" is a subsequence of \"abcde\" while \"aec\" is not). A common subsequence of two strings is a subsequence that is common to both strings"
  },
  {
    "_id": 96,
    "title": "Unique Binary Search Trees",
    "difficulty": "Medium",
    "topic": "Dynamic Programming, Tree,",
    "company": "Morgan Stanley",
    "typeOfInterview": "Personal Interview",
    "college": "IIIT, Una",
    "natureOfJob": "Full Time",
    "score": 85.807,
    "description": "Given two strings text1 and text2, return the length of their longest common subsequence.\n\nA subsequence of a string is a new string generated from the original string with some characters(can be none) deleted without changing the relative order of the remaining characters. (eg, \"ace\" is a subsequence of \"abcde\" while \"aec\" is not). A common subsequence of two strings is a subsequence that is common to both strings"
  },
  {
    "_id": 132,
    "title": "Palindrome Partitioning II",
    "difficulty": "Hard",
    "topic": "Dynamic Programming,",
    "company": "Xebia",
    "typeOfInterview": "Personal Interview",
    "college": "IIIT, Una",
    "natureOfJob": "Full Time",
    "score": 78.762,
    "description": "Invert a binary tree."
  },
  {
    "_id": 815,
    "title": "Bus Routes",
    "difficulty": "Hard",
    "topic": "Breadth-first Search,",
    "company": "Xebia",
    "typeOfInterview": "Personal Interview",
    "college": "IIIT, Una",
    "natureOfJob": "Internship",
    "score": 80.138,
    "description": "Given an array equations of strings that represent relationships between variables, each string equations[i] has length 4 and takes one of two different forms: \"a==b\" or \"a!=b\".  Here, a and b are lowercase letters (not necessarily different) that represent one-letter variable names.\n\nReturn true if and only if it is possible to assign integers to variable names so as to satisfy all the given equations."
  },
  {
    "_id": 309,
    "title": "Best Time to Buy and Sell Stock with Cooldown",
    "difficulty": "Medium",
    "topic": "Dynamic Programming,",
    "company": "Facebook",
    "typeOfInterview": "Personal Interview",
    "college": "IIIT, Una",
    "natureOfJob": "Internship",
    "score": 90.837,
    "description": "Given two strings word1 and word2, return the minimum number of operations required to convert word1 to word2.\n\nYou have the following three operations permitted on a word:\n\nInsert a character\nDelete a character\nReplace a character"
  },
  {
    "_id": 152,
    "title": "Maximum Product Subarray",
    "difficulty": "Medium",
    "topic": "Array, Dynamic Programming,",
    "company": "PayPal",
    "typeOfInterview": "Personal Interview",
    "college": "IIT, BHU",
    "natureOfJob": "Internship",
    "score": 91.034,
    "description": "Given an array equations of strings that represent relationships between variables, each string equations[i] has length 4 and takes one of two different forms: \"a==b\" or \"a!=b\".  Here, a and b are lowercase letters (not necessarily different) that represent one-letter variable names.\n\nReturn true if and only if it is possible to assign integers to variable names so as to satisfy all the given equations."
  },
  {
    "_id": 123,
    "title": "Best Time to Buy and Sell Stock III",
    "difficulty": "Hard",
    "topic": "Array, Dynamic Programming,",
    "company": "PayPal",
    "typeOfInterview": "Personal Interview",
    "college": "IIIT, Una",
    "natureOfJob": "Trainee",
    "score": 85.589,
    "description": "Given two strings word1 and word2, return the minimum number of operations required to convert word1 to word2.\n\nYou have the following three operations permitted on a word:\n\nInsert a character\nDelete a character\nReplace a character"
  },
  {
    "_id": 315,
    "title": "Count of Smaller Numbers After Self",
    "difficulty": "Hard",
    "topic": "Binary Search, Divide and Conquer, Sort, Binary Indexed Tree, Segment Tree,",
    "company": "DeMux",
    "typeOfInterview": "Online Test",
    "college": "SRMS",
    "natureOfJob": "Trainee",
    "score": 90.034,
    "description": "Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining."
  },
  {
    "_id": 1249,
    "title": "Minimum Remove to Make Valid Parentheses",
    "difficulty": "Medium",
    "topic": "String, Stack,",
    "company": "LinkedIn",
    "typeOfInterview": "Online Test",
    "college": "IIT, BHU",
    "natureOfJob": "Full Time",
    "score": 85.688,
    "description": "Invert a binary tree."
  },
  {
    "_id": 1388,
    "title": "Pizza With 3n Slices",
    "difficulty": "Hard",
    "topic": "Dynamic Programming,",
    "company": "Google",
    "typeOfInterview": "Online Test",
    "college": "IIIT, Una",
    "natureOfJob": "Trainee",
    "score": 95.54,
    "description": "Implement a trie with insert, search, and startsWith methods."
  },
  {
    "_id": 1449,
    "title": "Form Largest Integer With Digits That Add up to Target",
    "difficulty": "Hard",
    "topic": "String, Dynamic Programming,",
    "company": "Microsoft",
    "typeOfInterview": "Online Test",
    "college": "IIIT, Hyderabad",
    "natureOfJob": "Full Time",
    "score": 80.696,
    "description": "Invert a binary tree."
  },
  {
    "_id": 1278,
    "title": "Palindrome Partitioning III",
    "difficulty": "Hard",
    "topic": "Dynamic Programming,",
    "company": "Xebia",
    "typeOfInterview": "Personal Interview",
    "college": "NIT, Hamirpur",
    "natureOfJob": "Internship",
    "score": 90.8,
    "description": "Given two strings text1 and text2, return the length of their longest common subsequence.\n\nA subsequence of a string is a new string generated from the original string with some characters(can be none) deleted without changing the relative order of the remaining characters. (eg, \"ace\" is a subsequence of \"abcde\" while \"aec\" is not). A common subsequence of two strings is a subsequence that is common to both strings"
  },
  {
    "_id": 1312,
    "title": "Minimum Insertion Steps to Make a String Palindrome",
    "difficulty": "Hard",
    "topic": "Dynamic Programming,",
    "company": "Adobe",
    "typeOfInterview": "Personal Interview",
    "college": "NIT, Hamirpur",
    "natureOfJob": "Trainee",
    "score": 85.941,
    "description": "Implement a trie with insert, search, and startsWith methods."
  },
  {
    "_id": 131,
    "title": "Palindrome Partitioning",
    "difficulty": "Medium",
    "topic": "Backtracking,",
    "company": "Adobe",
    "typeOfInterview": "Personal Interview",
    "college": "IIT, BHU",
    "natureOfJob": "Internship",
    "score": 95.605,
    "description": "Given an array equations of strings that represent relationships between variables, each string equations[i] has length 4 and takes one of two different forms: \"a==b\" or \"a!=b\".  Here, a and b are lowercase letters (not necessarily different) that represent one-letter variable names.\n\nReturn true if and only if it is possible to assign integers to variable names so as to satisfy all the given equations."
  },
  {
    "_id": 1478,
    "title": "Allocate Mailboxes",
    "difficulty": "Hard",
    "topic": "Math, Dynamic Programming,",
    "company": "PayPal",
    "typeOfInterview": "Personal Interview",
    "college": "IIT, Roorkee",
    "natureOfJob": "Internship",
    "score": 95.6,
    "description": "Implement a trie with insert, search, and startsWith methods."
  },
  {
    "_id": 32,
    "title": "Longest Valid Parentheses",
    "difficulty": "Hard",
    "topic": "String, Stack,",
    "company": "Google",
    "typeOfInterview": "Online Test",
    "college": "IIIT, Una",
    "natureOfJob": "Full Time",
    "score": 85.539,
    "description": "Implement a trie with insert, search, and startsWith methods."
  },
  {
    "_id": 856,
    "title": "Score of Parentheses",
    "difficulty": "Medium",
    "topic": "String, Dynamic Programming,",
    "company": "Facebook",
    "typeOfInterview": "Online Test",
    "college": "IIT, Roorkee",
    "natureOfJob": "Part Time",
    "score": 90.054,
    "description": "Implement a trie with insert, search, and startsWith methods."
  },
  {
    "_id": 1368,
    "title": "Minimum Cost to Make at Least One Valid Path in a Grid",
    "difficulty": "Hard",
    "topic": "Breadth-first Search,",
    "company": "Jio",
    "typeOfInterview": "Online Test",
    "college": "SRMS",
    "natureOfJob": "Internship",
    "score": 97.838,
    "description": "Given two strings text1 and text2, return the length of their longest common subsequence.\n\nA subsequence of a string is a new string generated from the original string with some characters(can be none) deleted without changing the relative order of the remaining characters. (eg, \"ace\" is a subsequence of \"abcde\" while \"aec\" is not). A common subsequence of two strings is a subsequence that is common to both strings"
  },
  {
    "_id": 1125,
    "title": "Smallest Sufficient Team",
    "difficulty": "Hard",
    "topic": "Dynamic Programming, Bit Manipulation,",
    "company": "Morgan Stanley",
    "typeOfInterview": "Online Test",
    "college": "IIT, Roorkee",
    "natureOfJob": "Trainee",
    "score": 90.997,
    "description": "Given two strings text1 and text2, return the length of their longest common subsequence.\n\nA subsequence of a string is a new string generated from the original string with some characters(can be none) deleted without changing the relative order of the remaining characters. (eg, \"ace\" is a subsequence of \"abcde\" while \"aec\" is not). A common subsequence of two strings is a subsequence that is common to both strings"
  }
]


export const fetchResults = (startingId = 0) => {

  let obj = [];

  for (let i = startingId; i < startingId + RECORDS_PER_FETCH; i++) {
    if (data[i] === undefined)
      break;

    obj.push(data[i]);
  }
  return obj;
}


export const fetchResultsFilter = () => {

  let obj = [];

  for (let i = 0; i < 100; i++) {
    if (data[i] === undefined)
      break;

    obj.push(data[i]);
  }
  return obj;
}